name: Slack Notify Action
author: Vishal Kapse
description: Simple slack notification action using webhook url
inputs:
  SLACK_WEBHOOK_URL:
    description: Slack webhook URL
    required: true
  color:
    description: Color of slack banner notification
    required: false
    default: "#ff0000"
  message:
    description: Notification header to display in slack
    required: false
    default: "Github Actions workflow run has failed"

runs:
  using: node12
  main: 'dist/index.js'

branding:
  icon: "message-square"
  color: "#fa6019"