name: Simple Slack Notify Action
author: Vishal Kapse
description: Simple slack notification action using webhook url
inputs:
  SLACK_WEBHOOK_URL:
    description: Slack webhook URL
    required: true
  status:
    description: Status of workflow
    required: false
    default: failure
  message:
    description: Notification header to display in slack
    required: false
    default: "Github Actions workflow run details"

runs:
  using: node16
  main: 'dist/index.js'

branding:
  icon: "message-square"
  color: "orange"